kind: PersistentVolume
apiVersion: v1
metadata:
  name: redis-pv
  uid: 167a5635-ab57-44a2-ba1e-58de796eb471
  resourceVersion: '426751102'
  creationTimestamp: '2025-06-11T10:19:31Z'
  annotations:
    pv.kubernetes.io/bound-by-controller: 'yes'
  finalizers:
    - kubernetes.io/pv-protection
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: v1
      time: '2025-06-11T10:19:31Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:accessModes': {}
          'f:capacity':
            .: {}
            'f:storage': {}
          'f:nfs':
            .: {}
            'f:path': {}
            'f:server': {}
          'f:persistentVolumeReclaimPolicy': {}
          'f:volumeMode': {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: v1
      time: '2025-06-11T10:20:08Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:pv.kubernetes.io/bound-by-controller': {}
        'f:spec':
          'f:claimRef':
            .: {}
            'f:apiVersion': {}
            'f:kind': {}
            'f:name': {}
            'f:namespace': {}
            'f:resourceVersion': {}
            'f:uid': {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: v1
      time: '2025-06-11T10:20:08Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:phase': {}
      subresource: status
spec:
  capacity:
    storage: 1Gi
  nfs:
    server: 192.168.1.110
    path: /var/data
  accessModes:
    - ReadWriteMany
  claimRef:
    kind: PersistentVolumeClaim
    namespace: tprms
    name: pvc-redis
    uid: 649e03b3-4724-4d7e-bb79-72dc3d936633
    apiVersion: v1
    resourceVersion: '426751095'
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
status:
  phase: Bound
