kind: PersistentVolume
apiVersion: v1
metadata:
  name: static-azurefile-pv
  uid: 76518201-bfc8-405d-b03a-debc8cd29bc4
  resourceVersion: '428886077'
  creationTimestamp: '2025-06-13T12:36:54Z'
  annotations:
    pv.kubernetes.io/bound-by-controller: 'yes'
  finalizers:
    - kubernetes.io/pv-protection
  managedFields:
    - manager: kubectl-create
      operation: Update
      apiVersion: v1
      time: '2025-06-13T12:36:54Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:accessModes': {}
          'f:capacity':
            .: {}
            'f:storage': {}
          'f:nfs':
            .: {}
            'f:path': {}
            'f:server': {}
          'f:persistentVolumeReclaimPolicy': {}
          'f:volumeMode': {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: v1
      time: '2025-06-13T12:37:00Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:pv.kubernetes.io/bound-by-controller': {}
        'f:spec':
          'f:claimRef':
            .: {}
            'f:apiVersion': {}
            'f:kind': {}
            'f:name': {}
            'f:namespace': {}
            'f:resourceVersion': {}
            'f:uid': {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: v1
      time: '2025-06-13T12:37:00Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:phase': {}
      subresource: status
spec:
  capacity:
    storage: 1Gi
  nfs:
    server: 192.168.1.110
    path: /var/static-azurefile
  accessModes:
    - ReadWriteMany
  claimRef:
    kind: PersistentVolumeClaim
    namespace: tprms
    name: static-azurefile-pvc
    uid: b046f641-be0a-4a3a-acfa-9aa7d557d770
    apiVersion: v1
    resourceVersion: '428886075'
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
status:
  phase: Bound
