kind: PersistentVolume
apiVersion: v1
metadata:
  name: nginx-conf-azurefile-pv
  uid: a69d431d-9826-42bb-8a6c-f576536a9b6e
  resourceVersion: '428872556'
  creationTimestamp: '2025-06-13T12:17:05Z'
  annotations:
    pv.kubernetes.io/bound-by-controller: 'yes'
  finalizers:
    - kubernetes.io/pv-protection
  managedFields:
    - manager: kubectl-create
      operation: Update
      apiVersion: v1
      time: '2025-06-13T12:17:05Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:accessModes': {}
          'f:capacity':
            .: {}
            'f:storage': {}
          'f:nfs':
            .: {}
            'f:path': {}
            'f:server': {}
          'f:persistentVolumeReclaimPolicy': {}
          'f:volumeMode': {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: v1
      time: '2025-06-13T12:17:35Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:pv.kubernetes.io/bound-by-controller': {}
        'f:spec':
          'f:claimRef':
            .: {}
            'f:apiVersion': {}
            'f:kind': {}
            'f:name': {}
            'f:namespace': {}
            'f:resourceVersion': {}
            'f:uid': {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: v1
      time: '2025-06-13T12:17:35Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:phase': {}
      subresource: status
spec:
  capacity:
    storage: 1Gi
  nfs:
    server: 192.168.1.110
    path: /var/nginx-conf-azurefile
  accessModes:
    - ReadWriteMany
  claimRef:
    kind: PersistentVolumeClaim
    namespace: tprms
    name: nginx-conf-azurefile-pvc
    uid: e0be4c33-039a-4340-868b-995ff36d9207
    apiVersion: v1
    resourceVersion: '428872554'
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
status:
  phase: Bound
