kind: PersistentVolume
apiVersion: v1
metadata:
  name: nfs-pv
  uid: 346df02d-1e41-467a-b0db-173843ca48de
  resourceVersion: '99439075'
  creationTimestamp: '2024-07-22T09:48:46Z'
  annotations:
    pv.kubernetes.io/bound-by-controller: 'yes'
  finalizers:
    - kubernetes.io/pv-protection
  managedFields:
    - manager: kubectl-create
      operation: Update
      apiVersion: v1
      time: '2024-07-22T09:48:46Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:accessModes': {}
          'f:capacity': {}
          'f:nfs':
            .: {}
            'f:path': {}
            'f:server': {}
          'f:persistentVolumeReclaimPolicy': {}
          'f:volumeMode': {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: v1
      time: '2024-07-22T09:49:20Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:pv.kubernetes.io/bound-by-controller': {}
        'f:spec':
          'f:claimRef':
            .: {}
            'f:apiVersion': {}
            'f:kind': {}
            'f:name': {}
            'f:namespace': {}
            'f:resourceVersion': {}
            'f:uid': {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: v1
      time: '2024-07-22T09:49:20Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:phase': {}
      subresource: status
    - manager: Mozilla
      operation: Update
      apiVersion: v1
      time: '2024-07-22T10:29:30Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:capacity':
            'f:storage': {}
spec:
  capacity:
    storage: 2Gi
  nfs:
    server: 192.168.1.110
    path: /var/pv-pdf
  accessModes:
    - ReadWriteMany
  claimRef:
    kind: PersistentVolumeClaim
    namespace: saraswat-development
    name: nfs-pvc
    uid: 6b203017-6059-4c37-8895-7075ec2fed28
    apiVersion: v1
    resourceVersion: '99416215'
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
status:
  phase: Bound
