kind: Secret
apiVersion: v1
metadata:
  name: dynatrace-metadata-enrichment-endpoint
  namespace: tprms
  uid: 3b36d91c-bec8-49f6-a2ca-a69b3641f769
  resourceVersion: '448841844'
  creationTimestamp: '2025-07-02T09:48:58Z'
  labels:
    app.kubernetes.io/component: activegate
    app.kubernetes.io/created-by: lab-wcqdc
    app.kubernetes.io/name: dynatrace-operator
  annotations:
    internal.operator.dynatrace.com/template-hash: '3798125303'
  managedFields:
    - manager: dynatrace-operator
      operation: Update
      apiVersion: v1
      time: '2025-07-02T09:48:58Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:data':
          .: {}
          'f:endpoint.properties': {}
        'f:metadata':
          'f:annotations':
            .: {}
            'f:internal.operator.dynatrace.com/template-hash': {}
          'f:labels':
            .: {}
            'f:app.kubernetes.io/component': {}
            'f:app.kubernetes.io/created-by': {}
            'f:app.kubernetes.io/name': {}
        'f:type': {}
data:
  endpoint.properties: RFRfTUVUUklDU19JTkdFU1RfVVJMPWh0dHBzOi8vaXZpODQ0OTEubGl2ZS5keW5hdHJhY2UuY29tL2FwaS92Mi9tZXRyaWNzL2luZ2VzdApEVF9NRVRSSUNTX0lOR0VTVF9BUElfVE9LRU49ZHQwYzAxLklKV0VTV0pOU0VWNlIzTUY2MkFZUlhBUS42UUxENEdOM0VBSlNESlJFT1NYVk1BUUdPTEdIT1hJQk1RT1NLNkcyRkZNWk1ESlFSNERMSlJJUkhGWjNNNEdCCg==
type: Opaque
